### ISSUE TITLE
RuntimeError: CUDA error: operation not supported when calling `cusparseCreate(handle)`

### ISSUE THREAD

**Issue by Wayne3521** [qinzheng93/GeoTransformer#111]
According to the Readme: Ubuntu 20.04, GCC 9.3.0, Python 3.8, PyTorch 1.7.1, CUDA 11.1 and cuDNN 8.1.0.torch==1.7.1+cu110, the following problems occur：

Traceback (most recent call last):
  File "trainval.py", line 62, in <module>
    main()
  File "trainval.py", line 58, in main
    trainer.run()
  File "/home/wl/code/GeoTransformer/geotransformer/engine/epoch_based_trainer.py", line 180, in run
    self.train_epoch()
  File "/home/wl/code/GeoTransformer/geotransformer/engine/epoch_based_trainer.py", line 95, in train_epoch
    output_dict, result_dict = self.train_step(self.epoch, self.inner_iteration, data_dict)
  File "trainval.py", line 41, in train_step
    output_dict = self.model(data_dict)
  File "/home/wl/anaconda3/envs/geotransformer/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/wl/code/GeoTransformer/experiments/geotransformer.3dmatch.stage4.gse.k3.max.oacl.stage2.sinkhorn/model.py", line 198, in forward
    ref_corr_points, src_corr_points, corr_scores, estimated_transform = self.fine_matching(
  File "/home/wl/anaconda3/envs/geotransformer/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/wl/code/GeoTransformer/geotransformer/modules/geotransformer/local_global_registration.py", line 231, in forward
    ref_corr_points, src_corr_points, corr_scores, estimated_transform = self.local_to_global_registration(
  File "/home/wl/code/GeoTransformer/geotransformer/modules/geotransformer/local_global_registration.py", line 171, in local_to_global_registration
    batch_transforms = self.procrustes(batch_src_corr_points, batch_ref_corr_points, batch_corr_scores)
  File "/home/wl/anaconda3/envs/geotransformer/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/wl/code/GeoTransformer/geotransformer/modules/registration/procrustes.py", line 84, in forward
    return weighted_procrustes(
  File "/home/wl/code/GeoTransformer/geotransformer/modules/registration/procrustes.py", line 56, in weighted_procrustes
    **eye[:, -1, -1] = torch.sign(torch.det(V @ Ut))**
**RuntimeError: CUDA error: operation not supported when calling `cusparseCreate(handle)`**

**Comment by zhuozhizhong** [comment]
I meet the same question

**Comment by Wayne3521** [comment]
I haven't solved it yet

**Comment by Launch-on-Titania** [comment]
Generally, this issue is likely caused by your graphics card's CUDA and Torch versions being too old. 
In my case, using a 4090 with CUDA 11.6 and torch 1.12 resolved the error.

**Comment by zhuozhizhong** [comment]
> I haven't solved it yet

I solved this issue and didn't change my envirment setting.
```
    det = torch.det(V.cpu() @ Ut.cpu())
    eye[:, -1, -1] = torch.sign(det.cuda())
```

**Comment by Gatsbygreeen** [comment]
“ det = torch.det(V.cpu() @ Ut.cpu())
    eye[:, -1, -1] = torch.sign(det.cuda())”
I tried your method, but the problem still wasn't solved. Could you please explain in more detail how you made the changes? Thank you very much @zhuozhizhong #

**Comment by renatojmsdh** [comment]
Thanks! This solved for me too when running pytorch 1.7.1-cuda 11.0 in RTX 4090.

> 
> I solved this issue and didn't change my envirment setting.
> 
> ```
>     det = torch.det(V.cpu() @ Ut.cpu())
>     eye[:, -1, -1] = torch.sign(det.cuda())
> ```
